import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={ `${inter.className} border border-green-400 rounded-lg p-5 m-2` }>
        <p>Admin Root Layout</p>
        <nav><Link href={'/login'}>Open Login</Link></nav>
        {auth}
        {children}
      </body>
    </html>
  );
}
